#' Real Metagenomic Matrix
#'
#' A dataset containing real microbiome counts from [Describe Source/Study].
#' Rows are samples, columns are taxa.
#'
#' @format A numeric matrix with [X] rows and [Y] columns.
#' @source [Your Lab / Public Repository / Citation]
#' @usage data(real_counts)
"real_counts"

#' Synthetic Metagenomic Count Matrix
#'
#' A synthetic dataset generated by [Your Generator Name] intended to
#' mimic the 'real_counts' dataset.
#'
#' @format A numeric matrix with [X] rows and [Y] columns.
#' @usage data(synth_counts)
"synth_counts"
